name: Dockerize & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: davidwahid/surah-sender:latest
  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          port: ${{ secrets.DO_PORT }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSHKEY }}
          script: |
            cd ~/surah-sender
            docker pull davidwahid/surah-sender:latest
            docker stop surah-sender
            docker rm surah-sender
            docker run --name=surah-sender --restart=always --rm
